version: 0.0
os: linux
files:
  - source: target/hello-world-1.0-SNAPSHOT.jar
    destination: /root/App_3_Jave_samepleHelloWorld_jar/target/
hooks:
  AfterInstall:
    - location: start_server.sh
      timeout: 300
      runas: root
